name: Deploy to sample-rails-with-gha

on:
  # master ブランチにプッシュされた場合に動作する
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # GitHub リポジトリからコードを引っ張ってくる
      - name: Checkout
        uses: actions/checkout@v2
      # 前回のコンテナキャッシュがあれば使用する。なければキャッシュを作る
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # Ruby をインストールする
      - name: Set up Ruby 2.6.8
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.8
      # バンドラーをインストールし、初期化する
      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      # ヘロクにデプロイする
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fathomless-reaches-78667"
          heroku_email: "atsu.1130.2b@gmail.com"
